# Generated by Django 4.0.5 on 2022-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_date_of_birth_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='f', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('developer', 'Developer')], default='developer', max_length=10, verbose_name='User Type'),
        ),
    ]
