# Generated by Django 4.0.5 on 2022-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('account', '0011_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(null=True, to='tag.tag'),
        ),
    ]
