# Generated by Django 4.0.5 on 2022-06-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Inprogress', 'Inprogress'), ('Finished', 'Finished')], max_length=40)),
                ('Creation_time', models.DateField(verbose_name='Creation Time')),
                ('Modification_time', models.DateField(verbose_name='Modification Time')),
                ('Tags', models.ManyToManyField(to='tag.tag')),
            ],
        ),
    ]
